import re
from pathlib import Path

import pandas as pd

RAW_PATH = Path("dados_extraidos.csv")
CLEAN_PATH = Path("dados_limpos.csv")

COLUMN_RENAME = {
    "Código :": "codigo",
    "Referência:": "referencia",
    "Mercadoria:": "descricao",
    "Preço Compra:": "preco_compra",
    "Preço Venda:": "preco_venda",
    "Estoque:": "estoque",
    "Unnamed: 1": "unidade",
}

NUMERIC_COLUMNS = ["preco_compra", "preco_venda", "estoque"]


def clean_text_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.rename(columns=lambda name: name.strip())
    df = df.rename(columns=COLUMN_RENAME)

    # Drop completely empty columns and spare `Unnamed: 0` columns generated by pandas.
    drop_cols = [col for col in df.columns if col.startswith("Unnamed") or df[col].isna().all()]
    return df.drop(columns=drop_cols, errors="ignore")


def normalize_empty_cells(df: pd.DataFrame) -> pd.DataFrame:
    return df.replace(r"^\s*$", pd.NA, regex=True)


def merge_continuation_rows(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    previous = None

    def should_merge(row: pd.Series) -> bool:
        if pd.notna(row.get("codigo")):
            return False
        if pd.notna(row.get("referencia")) or pd.notna(row.get("descricao")) or pd.notna(row.get("unidade")):
            return True
        return False

    for _, row in df.iterrows():
        if should_merge(row) and previous is not None:
            extra_parts = []
            for field in ["referencia", "descricao", "unidade"]:
                value = row.get(field)
                if pd.notna(value):
                    extra_parts.append(str(value).strip())
            if extra_parts:
                previous["descricao"] = " ".join([str(previous.get("descricao", "")).strip(), " ".join(extra_parts)]).strip()
            if pd.isna(previous.get("unidade")) and pd.notna(row.get("unidade")):
                previous["unidade"] = row["unidade"]
            continue

        if previous is not None:
            rows.append(previous)
        previous = row.to_dict()

    if previous is not None:
        rows.append(previous)

    return pd.DataFrame(rows)


def parse_number(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).strip().replace(" ", "")
    if not text:
        return pd.NA

    # Translate Brazilian-style numbers: 1.234,56 -> 1234.56
    if "," in text:
        text = text.replace(".", "").replace(",", ".")

    try:
        return float(text)
    except ValueError:
        return pd.NA


def convert_numeric_columns(df: pd.DataFrame) -> pd.DataFrame:
    for col in NUMERIC_COLUMNS:
        if col in df.columns:
            df[col] = df[col].apply(parse_number)
            df[col] = df[col].astype("Float64")
    return df


def convert_id_columns(df: pd.DataFrame) -> pd.DataFrame:
    for col in ["codigo", "referencia"]:
        if col in df.columns:
            series = pd.to_numeric(df[col], errors="coerce")
            series = series.replace([float("inf"), float("-inf")], pd.NA)
            df[col] = series.astype("Int64")
    return df


def cleanup_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    df = normalize_empty_cells(df)
    df = clean_text_columns(df)
    df = merge_continuation_rows(df)
    df = df.dropna(subset=["descricao"], how="all")
    df = df.drop_duplicates()
    df = convert_numeric_columns(df)
    df = convert_id_columns(df)

    if "descricao" in df.columns:
        df["descricao"] = df["descricao"].astype(str).str.strip()

    return df


def main() -> None:
    raw_path = RAW_PATH
    clean_path = CLEAN_PATH

    if not raw_path.exists():
        raise FileNotFoundError(f"Arquivo não encontrado: {raw_path}")

    df = pd.read_csv(raw_path, dtype=str, keep_default_na=False)
    df = cleanup_dataframe(df)
    df.to_csv(clean_path, index=False)

    print(f"Limpeza concluída: {len(df)} linhas salvas em {clean_path}")


if __name__ == "__main__":
    main()
